spring.datasource.url=jdbc:postgresql://${DB_HOST}/hotel_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ddl-auto
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL for debugging
spring.jpa.show-sql=true

# Flyway config
spring.flyway.enabled=true

